[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyruse"
version = "1.0"
description = "Route systemd-journal logs to filters and actions (ban, report…)"
readme = { text = """
================
Python peruser of systemd-journal
================

This program is intended to be used as a lightweight replacement for both epylog and fail2ban.

The wanted features are these:

* Peruse all log entries from systemd’s journal, and only those (ie: no log files).
* Passively wait on new entries; no active polling.
* Filter-out uninteresting log lines according to the settings.
* Act on matches in the journal, with some pre-defined actions.
* Create a daily report with 2 parts:
    - events of interest (according to the settings),
    - and other non-filtered-out log entries.
* Send an immediate email when something important happens (according to the settings).
""", content-type = "text/x-rst" }
license = { text = "GPL-3" }
authors = [
    { name = "Yves G.", email = "theYinYeti@yalis.fr" }
]
maintainers = [
    { name = "Stefal"}
]

[project.urls]
Homepage = "https://yalis.fr/git/yves/pyruse"
Repository = "https://github.com/Stefal/pyruse"

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
pyruse = "pyruse.__main__:main"